namespace: oliverl_21
name: cisco_ios_update
version: 0.0.1
readme: README.md
description: role to update cisco ios
authors:
    - oliverl_21
repository: https://github.com/oliverl-21/ansible-role-ios_config
issues: https://github.com/oliverl-21/ansible-role-ios_config/issues
homepage: https://github.com/oliverl-21/ansible-role-ios_config
documentation: https://github.com/oliverl-21/ansible-role-ios_config
license:
    - "GPL-3.0-or-later"
tags:
    - networking
    - cisco
    - ios
    - iosxe
