---
# tasks file to update Cisco IOS-XE 8kv

- name: copy firmware file
  when: ansible_facts.net_model == "C8000V" and ansible_facts.net_version != updver
  cisco.ios.ios_command:
    commands:
      - command: 'copy {{ updmethod }}://{{ updserver }}{{ updpath }}{{ updfile }} flash:{{ updfile }}'
        prompt: 'Destination filename \[{{ updfile }}\]?'
        answer: "\r"
    wait_for: result[0] contains copied

- name: install firmware file
  when: ansible_facts.net_model == "C8000V" and ansible_facts.net_version != updver
  cisco.ios.ios_command:
    commands:
      - command: 'request platform software package install rp 0 file flash:{{ updfile }}'
    wait_for: result[0] contains SUCCESS

- name: save and reboot
  when: ansible_facts.net_model == "C8000V" and ansible_facts.net_version != updver
  cisco.ios.ios_command:
    commands:
      - command: "write memory"
      - command: "reload"
        prompt: 'Proceed with reload?'
        answer: "\r\n"
    wait_for: result[0] contains OK
  changed_when: True
  notify:
    - wait

- name: resetconnection
  meta: reset_connection

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: Gather default facts
  cisco.ios.ios_facts:
    gather_subset: min

- name: output current version
  debug:
    msg: "{{ ansible_facts.net_model }} running Version: {{ ansible_facts.net_version }}"
  changed_when: ansible_facts.net_version == updver
  notify:
    - clean_firmware
