---
# tasks file for Cisco IOS Update tasks
- name: Gather default facts
  cisco.ios.ios_facts:
    gather_subset: min

- name: output current version
  ansible.builtin.debug:
    msg: "{{ ansible_facts.net_model }} running Version: {{ ansible_facts.net_version }}"
  changed_when: ansible_facts.net_version != updver
  notify:
    - clean_firmware

- name: send Webex Status
  community.general.cisco_webex:
    recipient_type: "{{ webex_recipient_type }}"
    recipient_id: "{{ webex_recipient_id }}"
    msg_type: markdown
    personal_token: "{{ webex_token }}"
    msg: "### {{ ansible_facts.net_hostname }} needs to be updated.\n- Current Version:{{ ansible_facts.net_version }}\n- Target Version: {{ updver }}\n\n### Starting Install Task"
  when: ansible_facts.net_version != updver

- name: send Webex status
  community.general.cisco_webex:
    recipient_type: "{{ webex_recipient_type }}"
    recipient_id: "{{ webex_recipient_id }}"
    msg_type: markdown
    personal_token: "{{ webex_token }}"
    msg: "## {{ ansible_facts.net_hostname }} is already on target Version.\n- Current Version:{{ ansible_facts.net_version }}\n- Target Version: {{ updver }}\n\n### Install Task stopped for {{ ansible_facts.net_hostname }}"
  when: ansible_facts.net_version == updver

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers

- name: install XE
  ignore_unreachable: true
  import_tasks: install.yml
