---
# handlers for IOS Update Tasks

- name: wait
  wait_for:
    host: "{{ ansible_host }}"
    port: 22
    delay: 60
    timeout: 300
  delegate_to: localhost

- name: clean_firmware
  cisco.ios.ios_command:
    commands:
      - command: 'install commit'
      - command: 'install remove inactive'
        prompt: 'Do you want to proceed?'
        answer: 'y'
    wait_for: result[1] contains proceed or SUCCESS
